# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sensor:
  - id: !extend battery_power
    filters:
      multiply: 10
  - id: !extend battery_2_power
    filters:
      multiply: 10
  - id: !extend pv1_power
    filters:
      multiply: 10
  - id: !extend pv2_power
    filters:
      multiply: 10
  - id: !extend pv3_power
    filters:
      multiply: 10
  - id: !extend pv4_power
    filters:
      multiply: 10
  - id: !extend battery_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_2_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_bms_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_bms_charging_voltage
    filters:
      multiply: 0.1
  - id: !extend battery_bms_discharging_voltage
    filters:
      multiply: 0.1

number:
  - id: !extend generator_peak_shaving_power
    multiply: 0.1
    step: 10
  - id: !extend grid_peak_shaving_power
    multiply: 0.1
    step: 10
  - id: !extend max_sell_power
    multiply: 0.1
    step: 10
  - id: !extend max_solar_power
    multiply: 0.1
    step: 10
  - id: !extend zero_export_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_1_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_2_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_3_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_4_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_5_out_power
    multiply: 0.1
    step: 10
  - id: !extend time_of_use_6_out_power
    multiply: 0.1
    step: 10
switch:
  - id: !extend switch_time_of_use_1_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_2_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_3_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_4_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_5_sell
    disabled_by_default: false
  - id: !extend switch_time_of_use_6_sell
    disabled_by_default: false
