# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  update_interval: 3s
  update_interval_normal: 15s
  update_interval_slow: 300s

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description} by Lewa-Reka https://github.com/Lewa-Reka/esphome-deye-inverter"
  project:
    name: "lewa-reka.deye-inverter"
    version: "0.11.0"

logger:
  level: WARN

api:
  encryption:
    key: ${api_key}
  on_client_disconnected:
    - delay: ${safe_mode_delay}
    - if:
        condition:
          not: api.connected
        then:
          - logger.log: "Lost connection to HomeAssistant API - Activating safe mode"
          - script.execute: set_safe_modbus_registers

  on_client_connected:
    - logger.log: "Connection to HomeAssistant API restored"

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: ${fallback_password}

captive_portal:

uart:
  id: modbus_uart
  baud_rate: ${baud_rate}
  stop_bits: 1

modbus:
  id: modbus_1
  uart_id: modbus_uart
  turnaround_time: 100ms

modbus_controller:
  # FAST - sterowanie, bilans i stany przekaźników
  - id: ${modbus_controller_id}
    address: ${modbus_inverter_address}
    modbus_id: modbus_1
    setup_priority: -10
    update_interval: ${update_interval}
    offline_skip_updates: 3

  # NORMAL - telemetria diagnostyczna
  - id: deye_modbus_controller_normal
    address: ${modbus_inverter_address}
    modbus_id: modbus_1
    setup_priority: -10
    update_interval: ${update_interval_normal}
    offline_skip_updates: 3

  # SLOW - konfiguracja, liczniki i nastawy
  - id: deye_modbus_controller_slow
    address: ${modbus_inverter_address}
    modbus_id: modbus_1
    setup_priority: -10
    update_interval: ${update_interval_slow}
    offline_skip_updates: 3
